POST http://localhost:8000/api/transactions HTTP/1.1
content-type: application/json

{
  "transaction_type": "Kartu",
  "unit_id": 1,
  "station_id": 2,
  "flowmeter_start": 100,
  "flowmeter_end": 150,
  "hour_meter": 200,
  "driver_name": "Agus Santoso",
  "fuelman": "Budi",
  "remarks": "Coal Getting"
}

###

http://localhost:8000/api/transactions HTTP/1.1

content-type: application/json

{
  "transaction_type": "Kartu",
  "unit_id": 1,
  "station_id": 2,
  "flowmeter_start": 100,
  "flowmeter_end": 150,
  "hour_meter": 200,
  "driver_name": "Agus Santoso",
  "fuelman": "Budi",
  "remarks": "Coal Getting"
}

###

GET http://localhost:8000/api/vouchers/019a9477-bca0-729d-8033-6e9692419741 HTTP/1.1

###
PATCH http://localhost:8000/api/vouchers/019a9477-bca0-729d-8033-6e9692419741 HTTP/1.1
content-type: application/json

{
  "station_id": 1,
  "flowmeter_start": 5500,
  "hour_meter": 12.5,
  "transaction_date": "2025-01-18",
  "transaction_time": "08:30",
  "driver_name": "Asep",
  "fuelman": "Budi Speed",
  "remarks": "Isi pagi"
}

###

GET http://localhost:8000/api/units/0006601332 HTTP/1.1